# Generated by Django 4.1.5 on 2023-01-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='youtube_link',
            new_name='link',
        ),
    ]
